// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::animation_counter_type::AnimationCounter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `animation_counter`.
///
/// Obtain a handle from the [`AnimationCounterTableAccess::animation_counter`] method on [`super::RemoteTables`],
/// like `ctx.db.animation_counter()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.animation_counter().on_insert(...)`.
pub struct AnimationCounterTableHandle<'ctx> {
    imp: __sdk::TableHandle<AnimationCounter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `animation_counter`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AnimationCounterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AnimationCounterTableHandle`], which mediates access to the table `animation_counter`.
    fn animation_counter(&self) -> AnimationCounterTableHandle<'_>;
}

impl AnimationCounterTableAccess for super::RemoteTables {
    fn animation_counter(&self) -> AnimationCounterTableHandle<'_> {
        AnimationCounterTableHandle {
            imp: self.imp.get_table::<AnimationCounter>("animation_counter"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AnimationCounterInsertCallbackId(__sdk::CallbackId);
pub struct AnimationCounterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AnimationCounterTableHandle<'ctx> {
    type Row = AnimationCounter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AnimationCounter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AnimationCounterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AnimationCounterInsertCallbackId {
        AnimationCounterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AnimationCounterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AnimationCounterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AnimationCounterDeleteCallbackId {
        AnimationCounterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AnimationCounterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AnimationCounter>("animation_counter");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct AnimationCounterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AnimationCounterTableHandle<'ctx> {
    type UpdateCallbackId = AnimationCounterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AnimationCounterUpdateCallbackId {
        AnimationCounterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AnimationCounterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AnimationCounter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AnimationCounter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `animation_counter`,
/// which allows point queries on the field of the same name
/// via the [`AnimationCounterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.animation_counter().id().find(...)`.
pub struct AnimationCounterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AnimationCounter, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AnimationCounterTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `animation_counter`.
    pub fn id(&self) -> AnimationCounterIdUnique<'ctx> {
        AnimationCounterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AnimationCounterIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AnimationCounter> {
        self.imp.find(col_val)
    }
}
