// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::d_quat_type::DQuat;
use super::d_vec_3_type::DVec3;
use super::entity_type_type::EntityType;
use super::node_name_type::NodeName;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Entity {
    pub id: u64,
    pub node: NodeName,
    pub designation: String,
    pub relative_position: DVec3,
    pub relative_velocity: DVec3,
    pub relative_rotation: DQuat,
    pub relative_rotational_velocity: DVec3,
    pub mass: f64,
    pub max_impulse: DVec3,
    pub entity_type: EntityType,
}

impl __sdk::InModule for Entity {
    type Module = super::RemoteModule;
}
