// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::d_vec_3_type::DVec3;
use super::node_name_type::NodeName;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Node {
    pub id: u64,
    pub name: NodeName,
    pub parent_id: Option<u64>,
    pub node_position: DVec3,
    pub node_velocity: DVec3,
    pub node_rotation: DVec3,
    pub node_rotational_velocity: DVec3,
    pub orbit_progress: f64,
}

impl __sdk::InModule for Node {
    type Module = super::RemoteModule;
}
