// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum NodeName {
    Sun,

    Earth,

    Mars,

    Venus,

    Jupiter,

    Saturn,

    Uranus,

    Neptune,

    Pluto,

    Moon,

    Ceres,

    Eris,

    Haumea,

    Makemake,

    Phoebe,

    Titan,

    Callisto,

    Ganymede,

    Io,

    Europa,

    Enceladus,

    Triton,

    Charon,

    Titania,

    Oberon,

    Rhea,

    Iapetus,

    Dione,

    Tethys,

    Mimas,

    Hyperion,

    Ariel,

    Umbriel,

    Miranda,

    Custom(String),
}

impl __sdk::InModule for NodeName {
    type Module = super::RemoteModule;
}
