// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::test_reducer_schedule_type::TestReducerSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `test_reducer_schedule`.
///
/// Obtain a handle from the [`TestReducerScheduleTableAccess::test_reducer_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.test_reducer_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.test_reducer_schedule().on_insert(...)`.
pub struct TestReducerScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<TestReducerSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `test_reducer_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TestReducerScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TestReducerScheduleTableHandle`], which mediates access to the table `test_reducer_schedule`.
    fn test_reducer_schedule(&self) -> TestReducerScheduleTableHandle<'_>;
}

impl TestReducerScheduleTableAccess for super::RemoteTables {
    fn test_reducer_schedule(&self) -> TestReducerScheduleTableHandle<'_> {
        TestReducerScheduleTableHandle {
            imp: self
                .imp
                .get_table::<TestReducerSchedule>("test_reducer_schedule"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TestReducerScheduleInsertCallbackId(__sdk::CallbackId);
pub struct TestReducerScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TestReducerScheduleTableHandle<'ctx> {
    type Row = TestReducerSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TestReducerSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TestReducerScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TestReducerScheduleInsertCallbackId {
        TestReducerScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TestReducerScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TestReducerScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TestReducerScheduleDeleteCallbackId {
        TestReducerScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TestReducerScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TestReducerSchedule>("test_reducer_schedule");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct TestReducerScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TestReducerScheduleTableHandle<'ctx> {
    type UpdateCallbackId = TestReducerScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TestReducerScheduleUpdateCallbackId {
        TestReducerScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TestReducerScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TestReducerSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TestReducerSchedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `test_reducer_schedule`,
/// which allows point queries on the field of the same name
/// via the [`TestReducerScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.test_reducer_schedule().scheduled_id().find(...)`.
pub struct TestReducerScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TestReducerSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TestReducerScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `test_reducer_schedule`.
    pub fn scheduled_id(&self) -> TestReducerScheduleScheduledIdUnique<'ctx> {
        TestReducerScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TestReducerScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TestReducerSchedule> {
        self.imp.find(col_val)
    }
}
