// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::d_vec_3_type::DVec3;
use super::waypoint_type::Waypoint;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `waypoint`.
///
/// Obtain a handle from the [`WaypointTableAccess::waypoint`] method on [`super::RemoteTables`],
/// like `ctx.db.waypoint()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.waypoint().on_insert(...)`.
pub struct WaypointTableHandle<'ctx> {
    imp: __sdk::TableHandle<Waypoint>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `waypoint`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WaypointTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WaypointTableHandle`], which mediates access to the table `waypoint`.
    fn waypoint(&self) -> WaypointTableHandle<'_>;
}

impl WaypointTableAccess for super::RemoteTables {
    fn waypoint(&self) -> WaypointTableHandle<'_> {
        WaypointTableHandle {
            imp: self.imp.get_table::<Waypoint>("waypoint"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WaypointInsertCallbackId(__sdk::CallbackId);
pub struct WaypointDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WaypointTableHandle<'ctx> {
    type Row = Waypoint;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Waypoint> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WaypointInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WaypointInsertCallbackId {
        WaypointInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WaypointInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WaypointDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WaypointDeleteCallbackId {
        WaypointDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WaypointDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Waypoint>("waypoint");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct WaypointUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WaypointTableHandle<'ctx> {
    type UpdateCallbackId = WaypointUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WaypointUpdateCallbackId {
        WaypointUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WaypointUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Waypoint>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Waypoint>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `waypoint`,
/// which allows point queries on the field of the same name
/// via the [`WaypointIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.waypoint().id().find(...)`.
pub struct WaypointIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Waypoint, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WaypointTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `waypoint`.
    pub fn id(&self) -> WaypointIdUnique<'ctx> {
        WaypointIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WaypointIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Waypoint> {
        self.imp.find(col_val)
    }
}
