// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::d_vec_3_type::DVec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Waypoint {
    pub id: u64,
    pub entity_id: u64,
    pub target_position: DVec3,
    pub order_index: u32,
}

impl __sdk::InModule for Waypoint {
    type Module = super::RemoteModule;
}
